### ISSUE TITLE
database mysql not working

### ISSUE THREAD

**Issue by merry75** [SteffenGue/open-crypto#2] opened 2021-10-24 10:11 UTC
only sqlite worked for me
- Key request_method: Expected type(s) '<class 'str'>' != actual type '<class 'NoneType'>'.

also is it possible to use the same db and add tbl name field in config file  ? to add more tables to the same db

also it would be nice if you had a discord/telegram where you guys hang out where I could ask you a few questions about this project

thanks

**Comment by SteffenGue** [comment] 2021-10-25 05:54
Hi marry75!
Thanks for reaching out. The first problem you describe (not working MySQL database) should be fixed with the latest push. The issue occured due to different methods in the SQLAlchemy dialects. Specifically, we make use of ``on_conflict_do_nothing()`` to check for already existing primary keys:
```python
with self.session_scope() as session:
     stmt = self.insert_module.insert(db_table).values(data_to_persist)
     try:
         stmt = stmt.on_conflict_do_nothing(index_elements=primary_keys)
     except AttributeError:
         stmt = stmt.prefix_with("IGNORE")
     row_count = session.execute(stmt)
```
However, this method does not exist for MariaDB/MySQL but throws an ```AttributeError```, which makes a workaround necessary: [https://stackoverflow.com/questions/4596390/insert-on-duplicate-key-do-nothing/4596409](url)

Second, ```Key request_method: Expected type(s) '<class 'str'>' != actual type '<class 'NoneType'>'.``` is caused by the validation of the configuration file, right before the program starts. The statement is somewhat bulky, basically it says that the key ```request_method``` takes a string (```tickers```, ```trades```, ```order_books```, ```historic_rates```) but is instead not specified. Can you please check if that is the case?

Good idea with the Discord channel, I will consider creating one. Right now I'm working alone on the project, which is kind of a side-effect of my PhD study. However, if you have any questions in the meantime, feel free to send my a mail.

**Closed as completed** 2022-10-07 13:40 UTC
